#canvas constants
CANVAS_WIDTH = 1280
CANVAS_HEIGHT = 720

# gui constants
FONT_HEIGHT = 24
MARGIN = 12

#game constants
SHADOW_LAYER = 2
PLAYER_LAYER = 3
PLAYER_ARM_LAYER = 4
ABOVE_PLAYER = 5
BELOW_PLAYER = 1
BG_LAYER = 0
PARALLAX_LAYER = -1000
